# Assignment 1

## 2. Eigenvalue Decomposition

### (a) Compute the eigenvalue decomposition A = QΛQ^T with Λ = diag(λ_1 , λ_2).

In [ ]:
import numpy as np

A = 1/4* np.array([[7, -np.sqrt(3)],
                   [-np.sqrt(3), 5]])

# calculate eigenvalues & eigenvectors
# eigenvalues: [2, 1]
# values, vectors = np.linalg.eig(A)

# find eigenvalues
def pq_formula(p, q):
    p_half = -p/2
    sqrt = np.sqrt(p_half**2 - q)
    lamda_1 = p_half + sqrt 
    lamda_2 = p_half - sqrt
    return np.array([lamda_1, lamda_2])

def eigenvalues(matrix):
    # check if 2x2
    a = matrix[0,0]
    b = matrix[0,1]
    c = matrix[1,0]
    d = matrix[1,1]
    
    p = -(a+d)
    q = a*d-b*c
    
    eigenvals = pq_formula(p, q)
    
    return eigenvals

eigenvalues_of_A = eigenvalues(A)
print("eigenvalues(A):", eigenvalues_of_A)

In [24]:
find eigenvectors
def eigenvectors(matrix, eigenvals):
    for eigenval in eigenvals:
        B = matrix
        B[0,0] -= eigenval
        B[1,1] -= eigenval
        b_22_prime = B[1,1]*B[0,0] - B[0,1] * B[1,0]
        
        if b_22_prime < 0.00001:
            x_2 = 1
        else:
            x_2 = 0
        x_1 = 


Q = vectors

# Diagonalmatrix
V = np.zeros((2,2), int)
np.fill_diagonal(V,values)

# recreate A

def dot_product(matrix_A, matrix_B):
    matrix_temp = np.zeros((2,2))
    print(matrix_temp)
    
    return 0

print("dot_product:",dot_product(1,1))


B = np.dot(np.dot(Q,V), np.transpose(Q))
print("B: ", B)

eigenvalues(A): [ 2.  1.]
[[ 0.  0.]
 [ 0.  0.]]
dot_product: 0
B:  [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]]


In [39]:
%matplotlib inline

import matplotlib.pyplot as plt

def dx(f, x):
    return abs(0-f(x))
 
def newtons_method(f, df, x0, e):
    delta = dx(f, x0)
    while delta > e:
        x0 = x0 - f(x0)/df(x0)
        delta = dx(f, x0)
    print('Root is at: ', x0)
    print('f(x) at root is: ', f(x0))


def polynomial(coeffs, x):    
    value = 0
    x_exp = 1
    for coeff in coeffs:
        value += coeff * x_exp
        x_exp *= x
    return value
        
f_coeff =  [1, 2]

x = 2

f = polynomial(f_coeff)
f_1 = f(x)

plt.plot(f_1)
plt.show()


print("f_1: ", f_1)

TypeError: polynomial() missing 1 required positional argument: 'x'

### (b) Show that the columns of Q are orthonormal, i.e. the columns are of unit length and orthogonal.

In [4]:
# if Q.T * Q = I then Q is orthonormal 
# (normalized Eigenvectors)
print(np.transpose(Q).dot(Q))

[[1. 0.]
 [0. 1.]]


## c) Show that the matrix $QΛ^{-1}Q^T$ is the inverse of A 

In [5]:
# Q * V^-1 * Q.T = A^-1
print((Q.dot(np.linalg.inv(V))).dot(np.transpose(Q)))
print(np.linalg.inv(A))

[[0.625      0.21650635]
 [0.21650635 0.875     ]]
[[0.625      0.21650635]
 [0.21650635 0.875     ]]


## 4. Vector Norms

In [13]:
x_1 = [24, 3, 2, 31]
x_2 = [27, 20, 26, 21]
x_3 = [30, 21, 27, 5]
x_4 = [26, 28, 25, 14]


""""
def norm1(v):
        sum = 0
        for c in v:
            sum = sum + abs(c)
            norm1 = sum
        return norm1

print(norm1(x_1))

def norm2(v):
    sum = 0
    for c in v:
        sum = sum + np.square(abs(c))
        norm2 = np.sqrt(sum)
    return norm2

print(norm2(x_1))

"""

# we could substitute 8 with p and call with 1 for norm1 or 2 for norm2
def norm(v, p):
    sum = 0
    for c in v:
        sum = sum + abs(c)**p
        norm = sum**(1/p)
    return norm

print(norm(x_1, 1))

# Maximumsnorm, Betrag der betragsgrößten Komponente
def maxnorm(v):
    sum = 0
    for c in v:
        maxnorm = np.max(abs(c))
    return maxnorm

print(maxnorm(x_1))

60.0
31


In [14]:
# A in C umbenannt
C = [[3.5, np.sqrt(3)/2],
    [np.sqrt(3)/2, 2.5]]

def determinant(m):
    return m[0][0] * m[1][1] - m[0][1]* m[1][0]


def trace(m):
    return m[0][0] + m[1][1]

print(determinant(C))
print(trace(C))

# eigvalues = np.linalg.eig(C)?



8.0
6.0


In [18]:
import math

def Q(a):
    return [[math.cos(a), -math.sin(a)],
            [math.sin(a), math.cos(a)]]

def A_prime(a):
    return np.dot((np.dot(Q(a),(C))),
                  (np.transpose(Q(a))))

a_1 = math.pi/12
print(A_prime(a_1))
print(trace(A_prime(a_1)))
print(determinant(A_prime(a_1)))
print("eigenvalues(A_prime(a_1):", eigenvalues(A_prime(a_1)))
# TODO: Eigenvalues for A_prime


# (c) What would A_prime be for α = π / 3?
    

a_2 = math.pi/3
print(A_prime(a_2))

[[ 3.  1.]
 [ 1.  3.]]
6.0
8.0
eigenvalues(A_prime(a_1): [ 4.  2.]
[[  2.00000000e+00   2.22044605e-16]
 [  4.44089210e-16   4.00000000e+00]]
