#### Group Members

* Juliane Weilbach
* Amadeus Hovekamp
* Megan Klaiber

# Assignment 1

In [8]:
import numpy as np
from math import sqrt

### 1. Jupyter Notebooks

### (a) Compute the eigenvalue decomposition A = $QΛQ^T$ with $Λ = diag(λ_1 , λ_2)$.

In [9]:
import numpy as np

A = 1/4* np.array([[7, -np.sqrt(3)],
                   [-np.sqrt(3), 5]])

# A = np.array([[1, 0], [0,1]])

# calculate eigenvalues & eigenvectors
# eigenvalues: [2, 1]
# values, vectors = np.linalg.eig(A)

# find eigenvalues
def pq_formula(p, q):
    p_half = -p/2
    sqrt = np.sqrt(p_half**2 - q)
    lamda_1 = p_half + sqrt 
    lamda_2 = p_half - sqrt
    return np.array([lamda_1, lamda_2])

def eigenvalues(matrix):
    # check if matrix is quadratic and a 2x2 matrix
    dim = np.shape(matrix)
    if dim[0] != dim[1]:
        return 'Matrix is not quadratic!'
    elif dim[0] != 2:
        return 'Matrix is not a 2x2 Matrix!'
    else:
        a = matrix[0,0]
        b = matrix[0,1]
        c = matrix[1,0]
        d = matrix[1,1]

        p = -(a+d)
        q = a*d-b*c

        eigenvals = pq_formula(p, q)
    
        print('Eigenvalues:\n', eigenvals)
        return eigenvals

# compute eigenvectors
def eigenvectors(matrix, eigenvalues):
    
    
    return

# compute eigenvalue decomposition
def eigenvalue_decomposition(matrix):
    print('Matrix:\n', matrix)
    
    # check if matrix is quadratic and a 2x2 matrix
    dim = np.shape(matrix)
    if dim[0] != dim[1]:
        return 'Matrix is not quadratic!'
    elif dim[0] != 2:
        return 'Matrix is not a 2x2 Matrix!'
    else:
        # compute eigenvalues
        values = eigenvalues(matrix)
        # compute eigenvectors
        vectors = eigenvectors(matrix,values)

        Q = eigenvectors
        Lambda = np.diag(eigenvalues)

        print('\nDiagonal matrix Lambda with eigenvalues:\n', Lambda, '\n\nMatrix Q with eigenvectors as columns:\n', Q)

        print('\nSo A = Q * Lambda * Q.T:\n',Q * Lambda * np.transpose(Q))

    
A = 1/4 * np.matrix([[7, -sqrt(3)], [-sqrt(3), 5]])
eigenvalue_decomposition(A)



eigenvalues(A): [ 2.  1.]


In [26]:
# find eigenvectors
def eigenvectors(matrix, eigenvals):
    eigenvec = []
    a = matrix[0,0]
    b = matrix[0,1]
    c = matrix[1,0]
    d = matrix[1,1]
    if(c != 0):
        eigenvec.append([eigenvals[0]-d,c])
        eigenvec.append([eigenvals[1]-d,c])
    elif (b != 0):
        eigenvec.append([b,eigenvals[0] - a])
        eigenvec.append([b,eigenvals[1] - a])
    else:
        eigenvec.append([1,0])
        eigenvec.append([0,1])
    
    # print("before scaling:", eigenvec)
    for eigvec in eigenvec:
        length = np.sqrt(eigvec[0]**2+eigvec[1]**2)
        eigvec[0] /= length
        eigvec[1] /= length
    # print("after scaling:", eigenvec)
    return eigenvec


Q = np.array(eigenvectors(A, eigenvalues_of_A))

print("Q:", Q)
print("v:", Q[0])
print("|v|:", np.linalg.norm(Q[0]))

# compare to np.linalg.eig:
eigval, eigvec = np.linalg.eig(A.T)
print("eigval", eigval)
print("eigvec:", eigvec)

Q: [[ 0.8660254 -0.5      ]
 [-0.5       -0.8660254]]
v: [ 0.8660254 -0.5      ]
|v|: 1.0
eigval [ 2.  1.]
eigvec: [[ 0.8660254  0.5      ]
 [-0.5        0.8660254]]


In [40]:
# Diagonalmatrix
V = np.zeros((2,2), int)
np.fill_diagonal(V,values)

# recreate A

def dot_product(matrix_A, matrix_B):
    matrix_temp = np.zeros((2,2))
    print(matrix_temp)
    
    return 0

print("dot_product:",dot_product(1,1))


B = np.dot(np.dot(Q,V), np.transpose(Q))
print("B: ", B)

SyntaxError: invalid syntax (<ipython-input-40-2440420ed11d>, line 13)

In [39]:
%matplotlib inline

import matplotlib.pyplot as plt
def dx(f, x):
    return abs(0-f(x))
 
def newtons_method(f, df, x0, e):
    delta = dx(f, x0)
    while delta > e:
        x0 = x0 - f(x0)/df(x0)
        delta = dx(f, x0)
    print('Root is at: ', x0)
    print('f(x) at root is: ', f(x0))


def polynomial(coeffs, x):    
    value = 0
    x_exp = 1
    for coeff in coeffs:
        value += coeff * x_exp
        x_exp *= x
    return value
        
f_coeff =  [1, 2]

x = 2

f = polynomial(f_coeff)
f_1 = f(x)

plt.plot(f_1)
plt.show()


print("f_1: ", f_1)

TypeError: polynomial() missing 1 required positional argument: 'x'

### (b) Show that the columns of Q are orthonormal, i.e. the columns are of unit length and orthogonal.

In [4]:
# if Q.T * Q = I then Q is orthonormal 
# (normalized Eigenvectors)
print(np.transpose(Q).dot(Q))

[[1. 0.]
 [0. 1.]]


## c) Show that the matrix $QΛ^{-1}Q^T$ is the inverse of A 

In [5]:
# Q * V^-1 * Q.T = A^-1
print((Q.dot(np.linalg.inv(V))).dot(np.transpose(Q)))
print(np.linalg.inv(A))

[[0.625      0.21650635]
 [0.21650635 0.875     ]]
[[0.625      0.21650635]
 [0.21650635 0.875     ]]


## 4. Vector Norms

In [13]:
x_1 = [24, 3, 2, 31]
x_2 = [27, 20, 26, 21]
x_3 = [30, 21, 27, 5]
x_4 = [26, 28, 25, 14]


""""
def norm1(v):
        sum = 0
        for c in v:
            sum = sum + abs(c)
            norm1 = sum
        return norm1

print(norm1(x_1))

def norm2(v):
    sum = 0
    for c in v:
        sum = sum + np.square(abs(c))
        norm2 = np.sqrt(sum)
    return norm2

print(norm2(x_1))

"""

# we could substitute 8 with p and call with 1 for norm1 or 2 for norm2
def norm(v, p):
    sum = 0
    for c in v:
        sum = sum + abs(c)**p
        norm = sum**(1/p)
    return norm

print(norm(x_1, 1))

# Maximumsnorm, Betrag der betragsgrößten Komponente
def maxnorm(v):
    sum = 0
    for c in v:
        maxnorm = np.max(abs(c))
    return maxnorm

print(maxnorm(x_1))

60.0
31


In [14]:
# A in C umbenannt
C = [[3.5, np.sqrt(3)/2],
    [np.sqrt(3)/2, 2.5]]

def determinant(m):
    return m[0][0] * m[1][1] - m[0][1]* m[1][0]


def trace(m):
    return m[0][0] + m[1][1]

print(determinant(C))
print(trace(C))

# eigvalues = np.linalg.eig(C)?



8.0
6.0


In [18]:
import math

def Q(a):
    return [[math.cos(a), -math.sin(a)],
            [math.sin(a), math.cos(a)]]

def A_prime(a):
    return np.dot((np.dot(Q(a),(C))),
                  (np.transpose(Q(a))))

a_1 = math.pi/12
print(A_prime(a_1))
print(trace(A_prime(a_1)))
print(determinant(A_prime(a_1)))
print("eigenvalues(A_prime(a_1):", eigenvalues(A_prime(a_1)))
# TODO: Eigenvalues for A_prime


# (c) What would A_prime be for α = π / 3?
    

a_2 = math.pi/3
print(A_prime(a_2))

[[ 3.  1.]
 [ 1.  3.]]
6.0
8.0
eigenvalues(A_prime(a_1): [ 4.  2.]
[[  2.00000000e+00   2.22044605e-16]
 [  4.44089210e-16   4.00000000e+00]]
