Assignment 1

In [ ]:
import numpy as np

A = [[1.75, -(np.sqrt(3)/4)],
     [-(np.sqrt(3)/4), 1.25]]

# calculate eigenvalues & eigenvectors
# eigenvalues: [2, 1]
values, vectors = np.linalg.eig(A)

Q = vectors

# Diagonalmatrix
V = np.zeros((2,2), int)
np.fill_diagonal(V,values)

# recreate A
B = np.dot(np.dot(Q,V), np.transpose(Q))
print(B)

In [4]:
# if Q.T * Q = I then Q is orthonormal 
# (normalized Eigenvectors)
print(np.transpose(Q).dot(Q))

[[1. 0.]
 [0. 1.]]


In [5]:
# Q * V^-1 * Q.T = A^-1
print((Q.dot(np.linalg.inv(V))).dot(np.transpose(Q)))
print(np.linalg.inv(A))

[[0.625      0.21650635]
 [0.21650635 0.875     ]]
[[0.625      0.21650635]
 [0.21650635 0.875     ]]


In [6]:
x_1 = [24, 3, 2, 31]
x_2 = [27, 20, 26, 21]
x_3 = [30, 21, 27, 5]
x_4 = [26, 28, 25, 14]


""""
def norm1(v):
        sum = 0
        for c in v:
            sum = sum + abs(c)
            norm1 = sum
        return norm1

print(norm1(x_1))

def norm2(v):
    sum = 0
    for c in v:
        sum = sum + np.square(abs(c))
        norm2 = np.sqrt(sum)
    return norm2

print(norm2(x_1))

"""

# we could substitute 8 with p and call with 1 for norm1 or 2 for norm2
def norm(v, p):
    sum = 0
    for c in v:
        sum = sum + abs(c)**p
        norm = sum**(1/p)
    return norm

print(norm(x_1, 1))

# Maximumsnorm, Betrag der betragsgrößten Komponente
def maxnorm(v):
    sum = 0
    for c in v:
        maxnorm = np.max(abs(c))
    return maxnorm

print(maxnorm(x_1))

60.0
31


In [8]:
# A in C umbenannt
C = [[3.5, np.sqrt(3)/2],
    [np.sqrt(3)/2, 2.5]]

def determinant(m):
    return m[0][0] * m[1][1] - m[0][1]* m[1][0]


def trace(m):
    return m[0][0] + m[1][1]

print(determinant(C))
print(trace(C))

# TODO: eigvalues = np.linalg.eig(C)?



8.0
6.0


In [11]:
def Q(a):
    return [[m.cos(a), -m.sin(a)],
            [m.sin(a), m.cos(a)]]

def A_prime(a):
    return np.dot((np.dot(Q(a),(C))),
                  (np.transpose(Q(a))))

a_1 = m.pi/12
print(A_prime(a_1))
print(trace(A_prime(a_1)))
print(determinant(A_prime(a_1)))
# TODO: Eigenvalues for A_prime


# (c) What would A_prime be for α = π / 3?
    
import math as m
a_2 = m.pi/3
print(A_prime(a_2))

[[3. 1.]
 [1. 3.]]
6.0
8.000000000000002
[[2.00000000e+00 2.22044605e-16]
 [4.44089210e-16 4.00000000e+00]]
