#### Group Members

* Hovekamp, Amadeus
* Klaiber, Megan
* Weilbach, Juliane

In [15]:
import numpy as np
import scipy.linalg as la

#### help functions

In [16]:
# check if matrix is quadratic and a 2x2 matrix
def is_2x2_matrix(matrix):
    dim = np.shape(matrix)
    if dim[0] != dim[1]:
        print('Matrix is not quadratic!')
        return False
    elif dim[0] != 2:
        print('Matrix is not a 2x2 matrix!')
        return False
    else:
        return True


def matrixMultiplication(matrixA, matrixB):
    dimsA = np.shape(matrixA)
    dimsB = np.shape(matrixB)
    
    #print("matrixA\n", matrixA)
    #print("dimsA", dimsA)
    #print("matrixB\n", matrixB)
    #print("dimsB", dimsB)
    
    if(dimsA[1] != dimsB[0]):
        print("Error. Matrix dimensions do not fit!")
    else:
        # init result matrix with zeros of correct shape
        matrixC = np.zeros((dimsA[0], dimsB[1]))
        
        for rowA in range(0, dimsA[0]):
            for colB in range(0, dimsB[1]):
                for k in range(0, dimsA[1]):
                    matrixC[rowA, colB] += matrixA[rowA, k] * matrixB[k, colB]
        return matrixC
    
#A = np.array([[2,1],[1,1],[2,1]])
#B = np.array([[2,1,1],[3,2,3]])
#C = matrixMultiplication(A , B)
#C_correct = np.matmul(A , B)
#print("C\n", C)
#print("C_correct\n", C_correct)

## Assignment 1

### 1. Jupyter Notebooks

**(d)** It's useful for people who didn't work with jupyter notebooks yet.

### 2. Eigenvalue Decomposition
Given the matrix $A=\frac{1}{4}\left[ \begin{array}{rr}
7 & -\sqrt{3}  \\
-\sqrt{3} & 5  \\
\end{array}\right]$.

#### (a) Compute the eigenvalue decomposition $A=QΛQ^T$ with $Λ=diag(λ_1,λ_2)$.

In [17]:
A = 1/4 * np.array([[7, -np.sqrt(3)], [-np.sqrt(3), 5]])

# pq formula
def pq_formula(p, q):
    p_half = -p/2
    sqrt = np.sqrt(p_half**2 - q)
    lamda_1 = p_half + sqrt 
    lamda_2 = p_half - sqrt
    return np.array([lamda_1, lamda_2])

# compute eigenvalues
def eigenvalues(matrix):
    if is_2x2_matrix(matrix):
        a = matrix[0,0]
        b = matrix[0,1]
        c = matrix[1,0]
        d = matrix[1,1]

        p = -(a+d)
        q = a*d-b*c

        eigenvals = pq_formula(p, q)
    
        #print('Calculated eigenvalues:\n', eigenvals)
        return eigenvals
    else:
        print("Error! eigenvalues only supports 2x2 matrices!")

# compute eigenvectors
def eigenvectors(matrix, eigenvals):
    if is_2x2_matrix(matrix):
        eigenvec = []
        a = matrix[0,0]
        b = matrix[0,1]
        c = matrix[1,0]
        d = matrix[1,1]
        if c != 0:
            eigenvec.append([eigenvals[0]-d,c])
            eigenvec.append([eigenvals[1]-d,c])
        elif b != 0:
            eigenvec.append([b,eigenvals[0] - a])
            eigenvec.append([b,eigenvals[1] - a])
        else:
            eigenvec.append([1,0])
            eigenvec.append([0,1])

        # print("before scaling:", eigenvec)
        for eigvec in eigenvec:
            length = np.sqrt(eigvec[0]**2+eigvec[1]**2)
            eigvec[0] /= length
            eigvec[1] /= length
        # print("after scaling:", eigenvec)
        return eigenvec
    else:
        print("Error! eigenvectors only supports 2x2 matrices!")
    
# compute eigenvalue decomposition
def eigenvalue_decomposition(matrix):
    print('Matrix:\n', matrix)
    if is_2x2_matrix(matrix):
        # compute eigenvalues
        values = eigenvalues(matrix)
        # compute eigenvectors
        vectors = eigenvectors(matrix, values)
        
        Lambda = np.diag(values)
        Q = np.array(vectors)
        
        print('\nDiagonal matrix Lambda with eigenvalues:\n', Lambda,
              '\n\nMatrix Q with eigenvectors as columns:\n', Q)
        print('\nSo A = Q * Lambda * Q.T:\n',
              matrixMultiplication(matrixMultiplication(Q, Lambda) , np.transpose(Q)))
        return Lambda, Q
    else:
        print("Error! eigenvalue_decomposition only supports 2x2 matrices!")
        

'''
eigenvalues_of_A = eigenvalues(A)
print("Q:\n", Q)
print("v:\n", Q[0])
print("|v|:\n", np.linalg.norm(Q[0]))

# compare to np.linalg.eig:
eigval, eigvec = np.linalg.eig(A.T)
print("numpy eigval", eigval)
print("numpy eigvec:", eigvec)
'''
Lambda, Q = eigenvalue_decomposition(A)


Matrix:
 [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]]

Diagonal matrix Lambda with eigenvalues:
 [[ 2.  0.]
 [ 0.  1.]] 

Matrix Q with eigenvectors as columns:
 [[ 0.8660254 -0.5      ]
 [-0.5       -0.8660254]]

So A = Q * Lambda * Q.T:
 [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]]


#### (b) Show that the columns of Q are orthonormal, i.e. the columns are of unit length and orthogonal.

In [18]:
# compute the dot product of two vectors
def dot_product(vec1, vec2):
    dim_vec1 = np.shape(vec1)
    dim_vec2 = np.shape(vec2)
    # check if vectors have same dimension
    if dim_vec1 != dim_vec2:
        print('Input vectors have not the same dimension!')
    else:
        scalar = 0
        for i in range(0, dim_vec1[0]):
            scalar += vec1[i] * vec2[i]
        return round(scalar,2)
    
# compute the length of a vector
def vec_length(col):
    dim = np.shape(col)
    # check if input is a column
    if len(dim) != 1:
        print('Input is not a column!')
        return False
    else:
        x = 0
        for i in range(0,dim[0]):
            x += col[i]**2
        return np.sqrt(x)

# check if columns of a 2x2 matrix are orthonormal
def orthonormal_columns(matrix):
    # dimension of input matrix
    dim = np.shape(matrix)
    
    if is_2x2_matrix(matrix):
        # check if columns are of unit length
        for j in range(0,dim[1]):
            if vec_length(matrix[:,j]) != 1:
                print('Columns of the matrix are not of unit length!')
                return False

        # check if columns are orthognal
        if dot_product(matrix[:,0], matrix[:,1]) == 0:
            print('The columns of the matrix are orthonormal!')
            return True
        else:
            print('The columns of the matrix are not orthonormal!')
            return False
    else:
        print("Error! orthornormal_columns only supports 2x2 matrices!")
        
print('Q:\n',Q, '\n')
orthonormal_columns(Q)

Q:
 [[ 0.8660254 -0.5      ]
 [-0.5       -0.8660254]] 

The columns of the matrix are orthonormal!


True

#### (c) Show that the matrix $QΛ^{-1}Q^T$ is the inverse of A.

In [19]:
# calculate inverse for a 2x2 matrix
def inverse(matrix):
    if is_2x2_matrix(matrix):
        a = matrix[0,0]
        b = matrix[0,1]
        c = matrix[1,0]
        d = matrix[1,1]
        
        inv = 1 /(a*d-b*c) * np.array([[d, -b], [-c, a]])
    
        return inv
    else:
        print("Error! inverse only supports 2x2 matrices!")

print('Q:\n',Q, '\n')
print('Lambda:\n',Lambda, '\n')
print('Inverse of Lambda:\n', inverse(Lambda), '\n')

print('A:\n', A, '\n')
# inverse of A
print('Inverse of A:\n', inverse(A), '\n')
# result with matrix multiplication
print('\nSo inv(A) = Q * inv(Lambda) * Q.T:\n', matrixMultiplication( matrixMultiplication(Q, inverse(Lambda)),np.transpose(Q)))

Q:
 [[ 0.8660254 -0.5      ]
 [-0.5       -0.8660254]] 

Lambda:
 [[ 2.  0.]
 [ 0.  1.]] 

Inverse of Lambda:
 [[ 0.5 -0. ]
 [-0.   1. ]] 

A:
 [[ 1.75      -0.4330127]
 [-0.4330127  1.25     ]] 

Inverse of A:
 [[ 0.625       0.21650635]
 [ 0.21650635  0.875     ]] 


So inv(A) = Q * inv(Lambda) * Q.T:
 [[ 0.625       0.21650635]
 [ 0.21650635  0.875     ]]


**(d)** We invested approximately 4 hours for this exercise. It was time consuming to code all the simple things on our own.

### 3. Matrix Inversion
Given the matrix $A=\left[ \begin{array}{rr}
3 & 4  \\
6 & 13  \\
\end{array}\right]$.

#### (a) Compute $LU$ decomposition of it, i.e. $A=L\cdot U$, where *L* is a lowertriangular matrix and *U* is an uppertriangular matrix. Use this decomposition to solve $A\cdot x=b$ with $b=(1,2)^T$ via forward and backward substitution.

See: <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html"> SciPy Documentation for LU decomposition </a>
and
<a href="https://www.youtube.com/watch?v=rhNKncraJMk">  LU decomposition </a>

In [25]:
def lu_decomposition(matrix):
    dim = np.shape(matrix)
    # TODO!
    #L = matrix.copy()
    #U = np.ones((dim[0], dim[1]))
    for i in range(1,dim[0]-1): 
        print('i: ', i)
        for k in range(i+1, dim[0]):
            print('k: ', k)

            # calculate L
            matrix[k,i] = matrix[k,i] / matrix[i,i]
              
            for j in range(i+1, dim[0]):
                # calculate U
                matrix[k,j] = matrix[k,j] - matrix[k,i] * matrix[i,j]
    
    return matrix



A = np.array([[3, 4], [6, 13]])
print("A\n", A)

P, L, U = la.lu(A)
print("P\n", P)
print("L\n", L)
print("U\n", U)

print(lu_decomposition(A))


#L, U = lu_decomposition(A)
#print(matrixMultiplication(L,U))


b = np.array([1,2])


A
 [[ 3  4]
 [ 6 13]]
P
 [[ 0.  1.]
 [ 1.  0.]]
L
 [[ 1.   0. ]
 [ 0.5  1. ]]
U
 [[  6.   13. ]
 [  0.   -2.5]]
[[ 3  4]
 [ 6 13]]


#### (b) Use Gauss elimination to explicitly calculate the inverse of $A$ and show that it yields the same solution $x = A^{-1}\cdot b$ from part (a).

#### (c) TODO feedback

### 4. Vector Norms

#### (a) Compute the  $\lVert\cdot\rVert_{1}, \lVert\cdot\rVert_{2}, \lVert\cdot\rVert_{8}  $ and  $\lVert\cdot \rVert_{\infty} $ norms of the following vectors:  
<center>$x_{1} = \begin{pmatrix}24\\3\\2\\31\end{pmatrix}$, $x_{2} = \begin{pmatrix}27\\20\\26\\21\end{pmatrix}$, $x_{3} = \begin{pmatrix}30\\21\\27\\5\end{pmatrix} $ and $ x_{4} = \begin{pmatrix}26\\28\\25\\14\end{pmatrix}$.</center>



#### (b) Draw the set of points with $\lVert x\rVert_{i}$ for $i \in \{1,2,8,\infty\}$ and $x \in \mathbb{R}^{2}$.

#### (c) TODO feedback

### 5. Special Orthogonal Matrices

#### (a) Given the matrix 
<center>$A=\frac{1}{2}\left[ \begin{array}{rr}
7 & \sqrt{3}  \\
\sqrt{3} & 5  \\
\end{array}\right]$</center> 
#### compute $det(A), Tr(A)$ and its eigenvalues.

#### (b) The Matrix <center>$Q(\alpha)=\left[ \begin{array}{rr}
\cos{\alpha} & -\sin{\alpha}  \\
\sin{\alpha} & \cos{\alpha}  \\
\end{array}\right]$</center> 
#### represents a rotation around an axis by the angle $\alpha$. Compute $A^{\prime} = Q \cdot A \cdot Q^{T} ,$ det( $A^{\prime}$), Tr( $A^{\prime}$) and its eigenvalues for $\alpha = \frac{\pi}{12}$.

#### (c) What would $A^{\prime}$ be for $\alpha = \frac{\pi}{3}$?

#### (d) TODO feedback

In [ ]:
x_1 = [24, 3, 2, 31]
x_2 = [27, 20, 26, 21]
x_3 = [30, 21, 27, 5]
x_4 = [26, 28, 25, 14]


""""
def norm1(v):
        sum = 0
        for c in v:
            sum = sum + abs(c)
            norm1 = sum
        return norm1

print(norm1(x_1))

def norm2(v):
    sum = 0
    for c in v:
        sum = sum + np.square(abs(c))
        norm2 = np.sqrt(sum)
    return norm2

print(norm2(x_1))

"""

# we could substitute 8 with p and call with 1 for norm1 or 2 for norm2
def norm(v, p):
    sum = 0
    for c in v:
        sum = sum + abs(c)**p
        norm = sum**(1/p)
    return norm

print(norm(x_1, 1))

# Maximumsnorm, Betrag der betragsgrößten Komponente
def maxnorm(v):
    sum = 0
    for c in v:
        maxnorm = np.max(abs(c))
    return maxnorm

print(maxnorm(x_1))

In [ ]:
# A in C umbenannt
C = [[3.5, np.sqrt(3)/2],
    [np.sqrt(3)/2, 2.5]]

def determinant(m):
    return m[0][0] * m[1][1] - m[0][1]* m[1][0]


def trace(m):
    return m[0][0] + m[1][1]

print(determinant(C))
print(trace(C))

# eigvalues = np.linalg.eig(C)?



In [ ]:
import math

def Q(a):
    return [[math.cos(a), -math.sin(a)],
            [math.sin(a), math.cos(a)]]

def A_prime(a):
    return np.dot((np.dot(Q(a),(C))),
                  (np.transpose(Q(a))))

a_1 = math.pi/12
print(A_prime(a_1))
print(trace(A_prime(a_1)))
print(determinant(A_prime(a_1)))
print("eigenvalues(A_prime(a_1):", eigenvalues(A_prime(a_1)))
# TODO: Eigenvalues for A_prime


# (c) What would A_prime be for α = π / 3?
    

a_2 = math.pi/3
print(A_prime(a_2))